# Generated by Django 2.1.7 on 2019-03-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190317_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='addressid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purseid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Purse'),
        ),
    ]
